version: "3.9"

services:
  app:
    build: .
    container_name: mini-jira-node
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://mini_jira:password@postgres:5432/mini_jira?schema=public
      - REDIS_HOST=redis
      - IS_SCHEDULER=true
    depends_on:
      - postgres
      - redis

  worker-default:
    build: .
    container_name: mini-jira-worker-default
    restart: always
    command: npm run worker:default
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://mini_jira:password@postgres:5432/mini_jira?schema=public
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis

  worker-misc:
    build: .
    container_name: mini-jira-worker-misc
    restart: always
    command: npm run worker:misc
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://mini_jira:password@postgres:5432/mini_jira?schema=public
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    container_name: mini-jira-postgres
    restart: always
    environment:
      POSTGRES_USER: mini_jira
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mini_jira
      TZ: Asia/Kolkata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: mini-jira-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
